import:
	java.net.URL
	javax.imageio.ImageIO
	net.md_5.bungee.api.ChatColor
	java.awt.Color

function getSkinPixels(player: offline player, display.char: string="█") :: strings:
	set {_image} to ImageIO.read(new URL("https://cravatar.eu/helmavatar/%{_player}'s uuid%/8.png"))
	loop 8 times:
		loop 8 times:
			set {_line} to (loop-value-1 - 1)
			set {_skin::%{_line}%} to join {_skin::%{_line}%} and "%ChatColor.of(new Color({_image}.getRGB(loop-value-2 - 1, {_line})))%█"
	return {_skin::*}